import { createClient } from '@supabase/supabase-js'

export const supabase = createClient("https://kwiypgkubpkqnbedclhy.supabase.co", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3aXlwZ2t1YnBrcW5iZWRjbGh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzUyNTk3MjAsImV4cCI6MTk5MDgzNTcyMH0.jL1cyBWzrGH2jgrFPbubla4MmC4OjsaZ9iAGo9cl_pc")